/**
 * ResonanceConstants defines the magic numbers and layout constants
 * used throughout the Resonance simulation.
 */

import { Range } from "scenerystack/dot";

// ===== FONTS =====

const LABEL_FONT = 'bold 14px sans-serif';
const TITLE_FONT = 'bold 16px sans-serif';
const TICK_LABEL_FONT = '12px sans-serif';
const CONTROL_FONT = '14px sans-serif';

// ===== DRIVER BOX =====

const DRIVER_BOX_WIDTH = 600;
const DRIVER_BOX_HEIGHT = 120;
const DRIVER_BOX_CORNER_RADIUS = 10;
const DRIVER_BOX_LINE_WIDTH = 2;
const DRIVER_BOTTOM_MARGIN = 150; // distance from layout bounds bottom
const DRIVER_CENTER_X_OFFSET = -100; // offset from layout center

// ===== DRIVER CONTROLS =====

const CONTROL_SCALE = 0.7;
const POWER_TOGGLE_SPACING = 8;
const POWER_TOGGLE_LEFT = 15;
const POWER_TOGGLE_TOP = 15;
const FREQUENCY_CONTROL_TOP = 40;
const AMPLITUDE_CONTROL_LEFT = 10;
const AMPLITUDE_CONTROL_BOTTOM_MARGIN = 10;

// ===== PHYSICS RANGES =====

const FREQUENCY_RANGE = new Range( 0.1, 5 );
const AMPLITUDE_RANGE = new Range( 0, 10 );
const RESONATOR_COUNT_RANGE = new Range( 1, 10 );
const MASS_RANGE = new Range( 0.1, 10 );
const SPRING_CONSTANT_RANGE = new Range( 1, 200 );
const DAMPING_RANGE = new Range( 0, 10 );

// ===== SPRING AND MASS RENDERING =====

const EQUILIBRIUM_Y_OFFSET = 150; // pixels above driver top

// Mass node sizing: radius = max( MIN_MASS_RADIUS, MAX_MASS_RADIUS - count )
const MAX_MASS_RADIUS = 25;
const MIN_MASS_RADIUS = 10;
const MASS_STROKE_LINE_WIDTH = 3;

// ParametricSpringNode configuration
const SPRING_LOOPS = 10;
const SPRING_RADIUS = 5; // Reduced from 8 to make springs narrower
const SPRING_ASPECT_RATIO = 4;
const SPRING_POINTS_PER_LOOP = 40;
const SPRING_LINE_WIDTH = 1;
const SPRING_LEFT_END_LENGTH = 5;
const SPRING_RIGHT_END_LENGTH = 5;
const MIN_SPRING_XSCALE = 0.3;

// ===== RULER =====

const RULER_WIDTH = 300;
const RULER_HEIGHT = 40;
const RULER_MAJOR_TICK_WIDTH = 100;
const RULER_MINOR_TICKS_PER_MAJOR = 4;
const RULER_INSETS_WIDTH = 10;
const RULER_LEFT_MARGIN = 20;
const RULER_TOP_MARGIN = 50;

// ===== CONTROL PANEL =====

const CONTROL_PANEL_CORNER_RADIUS = 10;
const CONTROL_PANEL_LINE_WIDTH = 2;
const CONTROL_PANEL_X_MARGIN = 15;
const CONTROL_PANEL_Y_MARGIN = 15;
const CONTROL_PANEL_SPACING = 15;
const CONTROL_PANEL_RIGHT_MARGIN = 20;
const CONTROL_PANEL_TOP_MARGIN = 20;
const SEPARATOR_WIDTH = 250;

// ===== COMBO BOX =====

const COMBO_BOX_X_MARGIN = 10;
const COMBO_BOX_Y_MARGIN = 6;
const COMBO_BOX_CORNER_RADIUS = 5;
const COMBO_BOX_SPACING = 5;

// ===== GRAVITY =====

const GRAVITY_ACCELERATION = 9.8;
const GRAVITY_BOX_SPACING = 10;

// ===== RULER CHECKBOX =====

const RULER_CHECKBOX_BOX_WIDTH = 18;

// ===== RESET ALL BUTTON =====

const RESET_ALL_RIGHT_MARGIN = 20;
const RESET_ALL_BOTTOM_MARGIN = 20;

// ===== PLAYBACK CONTROLS =====

const STEP_DT = 0.016;
const PLAY_PAUSE_SCALE = 0.8;
const PLAYBACK_CONTROLS_SPACING = 10;
const SPEED_CONTROL_SPACING = 5;
const SPEED_RADIO_BUTTON_RADIUS = 8;
const PLAYBACK_BOTTOM_MARGIN = 20;

const ResonanceConstants = {
  // Fonts
  LABEL_FONT,
  TITLE_FONT,
  TICK_LABEL_FONT,
  CONTROL_FONT,

  // Driver box
  DRIVER_BOX_WIDTH,
  DRIVER_BOX_HEIGHT,
  DRIVER_BOX_CORNER_RADIUS,
  DRIVER_BOX_LINE_WIDTH,
  DRIVER_BOTTOM_MARGIN,
  DRIVER_CENTER_X_OFFSET,

  // Driver controls
  CONTROL_SCALE,
  POWER_TOGGLE_SPACING,
  POWER_TOGGLE_LEFT,
  POWER_TOGGLE_TOP,
  FREQUENCY_CONTROL_TOP,
  AMPLITUDE_CONTROL_LEFT,
  AMPLITUDE_CONTROL_BOTTOM_MARGIN,

  // Physics ranges
  FREQUENCY_RANGE,
  AMPLITUDE_RANGE,
  RESONATOR_COUNT_RANGE,
  MASS_RANGE,
  SPRING_CONSTANT_RANGE,
  DAMPING_RANGE,

  // Spring and mass rendering
  EQUILIBRIUM_Y_OFFSET,
  MAX_MASS_RADIUS,
  MIN_MASS_RADIUS,
  MASS_STROKE_LINE_WIDTH,
  SPRING_LOOPS,
  SPRING_RADIUS,
  SPRING_ASPECT_RATIO,
  SPRING_POINTS_PER_LOOP,
  SPRING_LINE_WIDTH,
  SPRING_LEFT_END_LENGTH,
  SPRING_RIGHT_END_LENGTH,
  MIN_SPRING_XSCALE,

  // Ruler
  RULER_WIDTH,
  RULER_HEIGHT,
  RULER_MAJOR_TICK_WIDTH,
  RULER_MINOR_TICKS_PER_MAJOR,
  RULER_INSETS_WIDTH,
  RULER_LEFT_MARGIN,
  RULER_TOP_MARGIN,

  // Control panel
  CONTROL_PANEL_CORNER_RADIUS,
  CONTROL_PANEL_LINE_WIDTH,
  CONTROL_PANEL_X_MARGIN,
  CONTROL_PANEL_Y_MARGIN,
  CONTROL_PANEL_SPACING,
  CONTROL_PANEL_RIGHT_MARGIN,
  CONTROL_PANEL_TOP_MARGIN,
  SEPARATOR_WIDTH,

  // Combo box
  COMBO_BOX_X_MARGIN,
  COMBO_BOX_Y_MARGIN,
  COMBO_BOX_CORNER_RADIUS,
  COMBO_BOX_SPACING,

  // Gravity
  GRAVITY_ACCELERATION,
  GRAVITY_BOX_SPACING,

  // Ruler checkbox
  RULER_CHECKBOX_BOX_WIDTH,

  // Reset all button
  RESET_ALL_RIGHT_MARGIN,
  RESET_ALL_BOTTOM_MARGIN,

  // Playback controls
  STEP_DT,
  PLAY_PAUSE_SCALE,
  PLAYBACK_CONTROLS_SPACING,
  SPEED_CONTROL_SPACING,
  SPEED_RADIO_BUTTON_RADIUS,
  PLAYBACK_BOTTOM_MARGIN
};

export default ResonanceConstants;
